### ISSUE TITLE
ERROR: could not find driver

### ISSUE THREAD

**Issue by Sanek911** [dlevsha/compalex#10]
![image](https://user-images.githubusercontent.com/24189705/27984497-342dfd82-63e0-11e7-908a-9f56a74a5fa6.png)

I setup Apache2.4.26(Win64) and PHP Version 7.0.21 added php_pdo_sqlsrv_7_ts_x64.dll and php_sqlsrv_7_ts_x64.dll. As result i got this error. Please give me the tip to solve this problem. Thank you.

**Comment by Sanek911** [comment]
Solved. 
Need to change params for PDO construct
new PDO("sqlsrv:server=$serverName ; Database=$baseName", $userName, $password);

**Comment by ihavenoidea14** [comment]
@Sanek911 Where did you make this change?

**Comment by danieljurican** [comment]
Hi,... i had same problem. I just hardcoded this function in file abstract.php

 ```
protected function _getConnect($dsn)   
    {  
        if (!isset($this->_dsn[$dsn])) {
            $pdsn = parse_url($dsn);
	if (DRIVER=="dblib") {	
	    $dsn = "sqlsrv:server=" . $pdsn['host'] ."  ; Database=" . substr($pdsn['path'], 1, 1000);	  
	}
	else{
	$dsn = DRIVER . ':host=' . $pdsn['host'] . ';port=' . $pdsn['port'] . ';dbname=' . substr($pdsn['path'], 1, 1000) . (DRIVER !== 'pgsql' ? ';charset=' . DATABASE_ENCODING : '');	
	}        
            $this->_dsn[$dsn] = new PDO($dsn, $pdsn['user'], isset($pdsn['pass']) ? $pdsn['pass'] : '', array(
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC
            ));
        }	
        return $this->_dsn[$dsn];
    }
```

**Comment by dlevsha** [comment]
Now you can use "sqlsrv" driver

DATABASE_DRIVER = sqlsrv
