### ISSUE TITLE
Warning with php > 7.1

### ISSUE THREAD

**Issue by webenhanced** [dlevsha/compalex#20]
When a table does not exist on either primary or secondary, the page displays the following php warning under the table name when using php versions greater than 7.1.

    Warning: count(): Parameter must be an array or an object that implements Countable in home/vagrant/Compalex/compalex/template/compare.php on line 72

This warning is also displayed on the CLI screen.

Sorry I have not had enough time to suggest a fix yet.

**Comment by dlevsha** [comment]
Fixed 
https://github.com/dlevsha/compalex/pull/17
