### ISSUE TITLE
Connection is Microsoft Azure SQL

### ISSUE THREAD

**Issue by SquallHalle** [dlevsha/compalex#23]
Hello i try to compare two Azure MS SQL Databases but i always get:
```
Compalex
Database schema compare tool
ERROR:
SQLSTATE[01002] Adaptive Server connection failed (COOLHOSTNAME:1433) (severity 9)
Stack trace:
#0 /usr/src/compalex/driver/abstract.php(34): PDO->__construct('dblib:host=COOL...', 'ACOOLUSERNAME...', 'CRYPTICPASSWORD...', Array)
#1 /usr/src/compalex/driver/abstract.php(17): BaseDriver->_getConnect('dblib:host=COOLHost...', 'cooldatabasename...')
#2 /usr/src/compalex/driver/abstract.php(65): BaseDriver->_getSecondConnect()
#3 /usr/src/compalex/driver/mssql.php(22): BaseDriver->_getCompareArray('SELECT DISTINCT...')
#4 /usr/src/compalex/index.php(28): Driver->getCompareTables()
#5 {main}
```
I added a dns server to the docker-compose so i am sure he can resolve the hostname, also i am sure about the used usernames/passwords/databasenames.

What could i do wrong ?

**Comment by austinwilcox** [comment]
Could it be that your azure database is encrypted? I am running into the same issue and the database I am trying to connect to is in azure, and is also encrypted.

edit: I realize your comment is now over 2 years old, and you never got a reply from the developer on this, so I may have to use a different solution to compare things.

**Comment by SquallHalle** [comment]
you are right. i used a different software.
